In [20]:
import torch

In [21]:
x = torch.Tensor([-1,2,3,4])
z = torch.unsqueeze(x, 0)
z

tensor([[-1.,  2.,  3.,  4.]])

In [23]:
z.T

tensor([[-1.],
        [ 2.],
        [ 3.],
        [ 4.]])

In [24]:
z

tensor([[-1.,  2.,  3.,  4.]])

可以看出返回张量与输入张量并没有共享内存

In [33]:
torch.manual_seed(1)
torch.initial_seed()
torch.get_rng_state()
# torch.set_rng_state(torch.Tensor([1, 2, 3]).byte())

tensor([1, 0, 0,  ..., 0, 0, 0], dtype=torch.uint8)